kind: ReplicationController
apiVersion: v1
metadata:
  name: go-demo
  labels:
    name: go-demo
spec:
  replicas: 1
  selector:
    name: go-demo
  template:
    metadata:
      labels:
        name: go-demo
    spec:
      containers:
      - name: go-demo
        image: 192.168.10.128:5000/go-demo
        command: ["sh","-c","msmgr http://ms:Microservice123!@20.26.33.122:32010"]
        ports:
        - containerPort: 8080
